name = "Biblioteca Bitcoin"
license = "MIT"
licenselink = "https://github.com/ventunobtc/bibliotecabitcoin/blob/master/LICENSE"
description = "Ho lavorato a un nuovo sistema di contante elettronico completamente peer-to-peer, senza terze parti fidate..."

homepage = "https://github.com/ventunobtc/bibliotecabitcoin"
demosite = "https://bibliotecabitcoin.netlify.app/"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]

[author]
  name = "cyphersats"
  homepage = ""
